name: Java CI with Maven + Cucumber

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # ðŸ§± Compila y empaqueta el proyecto
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      #run: mvn -B clean package --file pom.xml
      run: mvn -B package -DskipTests --file pom.xml
      
    # ðŸ§ª Ejecuta solo el runner de Cucumber (JUnit 5)
    #- name: Run Cucumber (JUnit 5)
      #run: mvn -B -ntp clean test -Dtest=RunCucumberTest
      #run: mvn -B -ntp test #-Dtest=RunCucumberTest
      #run: mvn -B -ntp clean verify -Dtest=RunCucumberTest
   # - name: Run Cucumber Tests    
    #  run: mvn -B -ntp test -Dtest=RunCucumberTest
    #vamos a modificar las siguientes lines, con estas dos ya corren los tres actions
    #- name: Run Cucumber (JUnit 5)
      #run: mvn -B -ntp test -Dtest=com.grupo.RunCucumberTest -Dcucumber.features=src/test/resources/features -Dcucumber.execution.strict=false
#por estas 7 lineas
    - name: Run Cucumber (JUnit 5)
      run: |
       mvn -B -ntp test \
       -Dtest=com.grupo.RunCucumberTest \
       -Dcucumber.features=src/test/resources/features \
       -Dcucumber.execution.strict=false \
       -Dcucumber.plugin="pretty,html:target/cucumber-report.html,json:target/cucumber.json"


    #se van a cambar las proximas lineas  
    # ðŸ“Š Publica los reportes de Cucumber como artifacts
    #- name: Publicar reporte Cucumber
     # if: always()
      #uses: actions/upload-artifact@v4
      #with:
       # name: cucumber-report
        #path: |
         # target/cucumber-report.html
          #target/cucumber.json
          
    - name: ðŸ“Š Publicar reporte Cucumber
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: |
          target/**/*.html
          target/**/*.json
        if-no-files-found: warn

